/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/bigScreen/': RouteRecordInfo<'/bigScreen/', '/bigScreen', Record<never, never>, Record<never, never>>,
    '/bigScreen/addBatch': RouteRecordInfo<'/bigScreen/addBatch', '/bigScreen/addBatch', Record<never, never>, Record<never, never>>,
    '/bigScreen/detail/': RouteRecordInfo<'/bigScreen/detail/', '/bigScreen/detail', Record<never, never>, Record<never, never>>,
    '/bigScreen/detail/camerTable': RouteRecordInfo<'/bigScreen/detail/camerTable', '/bigScreen/detail/camerTable', Record<never, never>, Record<never, never>>,
    '/bigScreen/detail/certificateTable': RouteRecordInfo<'/bigScreen/detail/certificateTable', '/bigScreen/detail/certificateTable', Record<never, never>, Record<never, never>>,
    '/bigScreen/detail/history/': RouteRecordInfo<'/bigScreen/detail/history/', '/bigScreen/detail/history', Record<never, never>, Record<never, never>>,
    '/bigScreen/detail/history/table': RouteRecordInfo<'/bigScreen/detail/history/table', '/bigScreen/detail/history/table', Record<never, never>, Record<never, never>>,
    '/bigScreen/detail/history/table2': RouteRecordInfo<'/bigScreen/detail/history/table2', '/bigScreen/detail/history/table2', Record<never, never>, Record<never, never>>,
    '/bigScreen/detail/readerTable': RouteRecordInfo<'/bigScreen/detail/readerTable', '/bigScreen/detail/readerTable', Record<never, never>, Record<never, never>>,
    '/bigScreen/detail/team-card': RouteRecordInfo<'/bigScreen/detail/team-card', '/bigScreen/detail/team-card', Record<never, never>, Record<never, never>>,
    '/bigScreen/detail/team-info': RouteRecordInfo<'/bigScreen/detail/team-info', '/bigScreen/detail/team-info', Record<never, never>, Record<never, never>>,
    '/bigScreen/detail/test': RouteRecordInfo<'/bigScreen/detail/test', '/bigScreen/detail/test', Record<never, never>, Record<never, never>>,
    'MainTain': RouteRecordInfo<'MainTain', '/bigScreen/mainTain', Record<never, never>, Record<never, never>>,
    '/bigScreen/module/addMore': RouteRecordInfo<'/bigScreen/module/addMore', '/bigScreen/module/addMore', Record<never, never>, Record<never, never>>,
    '/bigScreen/module/finishedProduct': RouteRecordInfo<'/bigScreen/module/finishedProduct', '/bigScreen/module/finishedProduct', Record<never, never>, Record<never, never>>,
    '/bigScreen/module/printPage': RouteRecordInfo<'/bigScreen/module/printPage', '/bigScreen/module/printPage', Record<never, never>, Record<never, never>>,
    '/bigScreen/module/startPage': RouteRecordInfo<'/bigScreen/module/startPage', '/bigScreen/module/startPage', Record<never, never>, Record<never, never>>,
    '/bigScreen/newIndex': RouteRecordInfo<'/bigScreen/newIndex', '/bigScreen/newIndex', Record<never, never>, Record<never, never>>,
    'SetPage': RouteRecordInfo<'SetPage', '/bigScreen/setting', Record<never, never>, Record<never, never>>,
    '/bigScreen/setting/onlyTest/': RouteRecordInfo<'/bigScreen/setting/onlyTest/', '/bigScreen/setting/onlyTest', Record<never, never>, Record<never, never>>,
    '/bigScreen/setting/print/': RouteRecordInfo<'/bigScreen/setting/print/', '/bigScreen/setting/print', Record<never, never>, Record<never, never>>,
    '/bigScreen/setting/startSet/process': RouteRecordInfo<'/bigScreen/setting/startSet/process', '/bigScreen/setting/startSet/process', Record<never, never>, Record<never, never>>,
    '/bigScreen/setting/startSet/reader': RouteRecordInfo<'/bigScreen/setting/startSet/reader', '/bigScreen/setting/startSet/reader', Record<never, never>, Record<never, never>>,
    '/bigScreen/setting/startSet/turnline': RouteRecordInfo<'/bigScreen/setting/startSet/turnline', '/bigScreen/setting/startSet/turnline', Record<never, never>, Record<never, never>>,
    'Main': RouteRecordInfo<'Main', '/Module', Record<never, never>, Record<never, never>>,
    'TestModal': RouteRecordInfo<'TestModal', '/Module/indexPage', Record<never, never>, Record<never, never>>,
    '/Module/info': RouteRecordInfo<'/Module/info', '/Module/info', Record<never, never>, Record<never, never>>,
    '/Module/ModuleForm': RouteRecordInfo<'/Module/ModuleForm', '/Module/ModuleForm', Record<never, never>, Record<never, never>>,
    '/Module/transfer': RouteRecordInfo<'/Module/transfer', '/Module/transfer', Record<never, never>, Record<never, never>>,
    '/test': RouteRecordInfo<'/test', '/test', Record<never, never>, Record<never, never>>,
  }
}
