/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/bigScreen/': RouteRecordInfo<'/bigScreen/', '/bigScreen', Record<never, never>, Record<never, never>>,
    '/bigScreen/addMore': RouteRecordInfo<'/bigScreen/addMore', '/bigScreen/addMore', Record<never, never>, Record<never, never>>,
    '/bigScreen/finishedProduct': RouteRecordInfo<'/bigScreen/finishedProduct', '/bigScreen/finishedProduct', Record<never, never>, Record<never, never>>,
    '/bigScreen/printPage': RouteRecordInfo<'/bigScreen/printPage', '/bigScreen/printPage', Record<never, never>, Record<never, never>>,
    '/bigScreen/startPage': RouteRecordInfo<'/bigScreen/startPage', '/bigScreen/startPage', Record<never, never>, Record<never, never>>,
    '/Info/': RouteRecordInfo<'/Info/', '/Info', Record<never, never>, Record<never, never>>,
    'Main': RouteRecordInfo<'Main', '/Module', Record<never, never>, Record<never, never>>,
    'TestModal': RouteRecordInfo<'TestModal', '/Module/indexPage', Record<never, never>, Record<never, never>>,
    '/Module/ModuleForm': RouteRecordInfo<'/Module/ModuleForm', '/Module/ModuleForm', Record<never, never>, Record<never, never>>,
    '/Module/transfer': RouteRecordInfo<'/Module/transfer', '/Module/transfer', Record<never, never>, Record<never, never>>,
    '/test/antd-table': RouteRecordInfo<'/test/antd-table', '/test/antd-table', Record<never, never>, Record<never, never>>,
    '/test/father': RouteRecordInfo<'/test/father', '/test/father', Record<never, never>, Record<never, never>>,
    '/test/list': RouteRecordInfo<'/test/list', '/test/list', Record<never, never>, Record<never, never>>,
    '/test/list-item': RouteRecordInfo<'/test/list-item', '/test/list-item', Record<never, never>, Record<never, never>>,
    '/test/seamless-scroll': RouteRecordInfo<'/test/seamless-scroll', '/test/seamless-scroll', Record<never, never>, Record<never, never>>,
  }
}
