/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/bigScreen/': RouteRecordInfo<'/bigScreen/', '/bigScreen', Record<never, never>, Record<never, never>>,
    '/bigScreen/mainTain': RouteRecordInfo<'/bigScreen/mainTain', '/bigScreen/mainTain', Record<never, never>, Record<never, never>>,
    '/bigScreen/module/addMore': RouteRecordInfo<'/bigScreen/module/addMore', '/bigScreen/module/addMore', Record<never, never>, Record<never, never>>,
    '/bigScreen/module/finishedProduct': RouteRecordInfo<'/bigScreen/module/finishedProduct', '/bigScreen/module/finishedProduct', Record<never, never>, Record<never, never>>,
    '/bigScreen/module/printPage': RouteRecordInfo<'/bigScreen/module/printPage', '/bigScreen/module/printPage', Record<never, never>, Record<never, never>>,
    '/bigScreen/module/startPage': RouteRecordInfo<'/bigScreen/module/startPage', '/bigScreen/module/startPage', Record<never, never>, Record<never, never>>,
    '/bigScreen/printPage': RouteRecordInfo<'/bigScreen/printPage', '/bigScreen/printPage', Record<never, never>, Record<never, never>>,
    'TestModal': RouteRecordInfo<'TestModal', '/bigScreen/setPage', Record<never, never>, Record<never, never>>,
    '/bigScreen/setting/startSet': RouteRecordInfo<'/bigScreen/setting/startSet', '/bigScreen/setting/startSet', Record<never, never>, Record<never, never>>,
    'Main': RouteRecordInfo<'Main', '/Module', Record<never, never>, Record<never, never>>,
    'TestModal': RouteRecordInfo<'TestModal', '/Module/indexPage', Record<never, never>, Record<never, never>>,
    '/Module/info': RouteRecordInfo<'/Module/info', '/Module/info', Record<never, never>, Record<never, never>>,
    '/Module/ModuleForm': RouteRecordInfo<'/Module/ModuleForm', '/Module/ModuleForm', Record<never, never>, Record<never, never>>,
    '/Module/transfer': RouteRecordInfo<'/Module/transfer', '/Module/transfer', Record<never, never>, Record<never, never>>,
  }
}
