name: Build and Release Electron App

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        architecture: [x64] # 指定架构
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install yarn
        run: |
          npm install -g yarn
          echo "$(npm bin -g)" >> $GITHUB_PATH

      - name: Install dependencies
        run: yarn

      - name: Install Ruby and fpm
        run: |
          sudo apt update
          sudo apt install ruby -y
          sudo gem install fpm

      - name: Get Version Number
        id: get_version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Build the Electron app
        env:
          USE_SYSTEM_FPM: "true"
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn run build:linux

      - name: Upload Specific Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.architecture }}
          path: |
            ./release/${{ env.VERSION }}/*
            !**/linux-unpacked/**
          if-no-files-found: error # 如果未找到文件，则抛出错误

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release/${{ env.VERSION }} # 将所有制品下载到 release/${{ env.VERSION }} 目录

      - name: Compress artifacts
        run: |
          cd release/${{ env.VERSION }}
          zip -r ../release-${{ github.ref_name }}.zip .

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} release-${{ github.ref_name }}.zip \
            --generate-notes \
            --title "Release ${{ github.ref_name }}"
